# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Install dependencies
WORKDIR /app
COPY weather.py .

# Install Python dependencies
RUN pip install --no-cache-dir httpx mcp

# Expose stdin/stdout server
CMD ["python", "weather.py"]
